### PR TITLE
translate remaining messages to pt

### PR DESCRIPTION
**Pull request by waldyrious**
also adjust some of the previous translations to make the meaning clearer

### CODE REVIEW

**Comment by drinckes** [comment]
I just saw your pull request after uploading new PT translations. These ones include all the messages.

Sorry - if you spot errors or have corrections let me know and I'll try to respond faster.

**Comment by waldyrious** [comment]
I won't lie, this is fairly disheartening and doesn't encourage me at all to contribute further. In fact, this has happened way too often in my experience—just the other day someone [replied in another repo to a message I had written back in 2011](https://github.com/edsu/wikistream/issues/15#issuecomment-114521963)—, so I can only assume something must be terribly wrong with github's notification system. Care to share why you missed this PR?

**Comment by drinckes** [comment]
I think it just got lost in my mailbox - I don't have a very good reason, I'm sorry. I do really appreciate what you did up to now, it was super useful, and I hope you still feel willing to contribute to projects.

**Comment by waldyrious** [comment]
Ok, thanks. I guess maybe github could ping regularly owners of repositories with pending PRs, since this seems to happen a lot (not to mention completely abandoned repos), but apart from that there isn't much it can do, I suppose. I will still keep this project under watch and contribute if I feel I can, but I hope you'll understand if I don't take the time to compare my translations with the ones just uploaded. No hard feelings, I just can't muster up the motivation for this particular contribution not to feel like work :)

**Pull request closed without merging**
